dataset:
  train:
    class: CoDesignDataset
    mmap_dir: ./datasets/train_valid/processed
    specify_index: ./datasets/train_valid/processed/train_index.txt
    backbone_only: false
    cluster: ./datasets/train_valid/train.cluster
  valid:
    class: CoDesignDataset
    mmap_dir: ./datasets/train_valid/processed
    specify_index: ./datasets/train_valid/processed/valid_index.txt
    backbone_only: false

dataloader:
  shuffle: true
  num_workers: 4
  wrapper:
    class: DynamicBatchWrapper
    complexity: n**2
    ubound_per_batch: 60000  # batch size ~24

trainer:
  class: AutoEncoderTrainer
  config:
    max_epoch: 500 # the best checkpoint should be obatained at about epoch 457
    save_topk: 10
    save_dir: ./ckpts/autoencoder_fixseq
    patience: 10
    metric_min_better: true

    optimizer:
      class: AdamW
      lr: 1.0e-4
    
    scheduler:
      class: ReduceLROnPlateau
      factor: 0.8
      patience: 15
      mode: min
      frequency: val_epoch
      min_lr: 5.0e-6

model:
  class: AutoEncoder
  embed_size: 128
  hidden_size: 128
  latent_size: 0
  latent_n_channel: 1
  n_layers: 3
  n_channel: 14  # all atom
  h_kl_weight: 0.0
  z_kl_weight: 1.0
  coord_loss_ratio: 1.0
  coord_loss_weights:
    Xloss: 1.0
    ca_Xloss: 1.0
    bb_bond_lengths_loss: 1.0
    sc_bond_lengths_loss: 1.0
    bb_dihedral_angles_loss: 0.0
    sc_chi_angles_loss: 0.5
  anchor_at_ca: true
  mode: fixseq
